services:
  backend:
    container_name: backend
    build:
      context: ./ # Ensure correct directory
      dockerfile: WMA-4.0-Express.dockerfile
    ports:
      - 3001:3001
    env_file: .env

  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      
volumes:
  db_data: {}
