name: wma-4

services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: WMA-4.0-Express.dockerfile
    ports:
      - 3001:3001
    env_file: .env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
